// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
)

const createItemCategory = `-- name: CreateItemCategory :one
INSERT INTO item_categories (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateItemCategory(ctx context.Context, name string) (ItemCategory, error) {
	row := q.db.QueryRowContext(ctx, createItemCategory, name)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createMealCategory = `-- name: CreateMealCategory :one
INSERT INTO meal_categories (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateMealCategory(ctx context.Context, name string) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, createMealCategory, name)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteItemCategory = `-- name: DeleteItemCategory :exec
DELETE FROM item_categories WHERE id = $1
`

func (q *Queries) DeleteItemCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteItemCategory, id)
	return err
}

const deleteMealCategory = `-- name: DeleteMealCategory :exec
DELETE FROM meal_categories WHERE id = $1
`

func (q *Queries) DeleteMealCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMealCategory, id)
	return err
}

const getItemCategory = `-- name: GetItemCategory :one
SELECT id, name FROM item_categories WHERE id = $1
`

func (q *Queries) GetItemCategory(ctx context.Context, id int32) (ItemCategory, error) {
	row := q.db.QueryRowContext(ctx, getItemCategory, id)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getItemCategoryByName = `-- name: GetItemCategoryByName :one
SELECT id, name FROM item_categories WHERE name = $1
`

func (q *Queries) GetItemCategoryByName(ctx context.Context, name string) (ItemCategory, error) {
	row := q.db.QueryRowContext(ctx, getItemCategoryByName, name)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getMealCategory = `-- name: GetMealCategory :one
SELECT id, name FROM meal_categories WHERE id = $1
`

func (q *Queries) GetMealCategory(ctx context.Context, id int32) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, getMealCategory, id)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getMealCategoryByName = `-- name: GetMealCategoryByName :one
SELECT id, name FROM meal_categories WHERE name = $1
`

func (q *Queries) GetMealCategoryByName(ctx context.Context, name string) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, getMealCategoryByName, name)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listItemCategories = `-- name: ListItemCategories :many
SELECT id, name FROM item_categories ORDER BY name ASC
`

func (q *Queries) ListItemCategories(ctx context.Context) ([]ItemCategory, error) {
	rows, err := q.db.QueryContext(ctx, listItemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemCategory
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealCategories = `-- name: ListMealCategories :many
SELECT id, name FROM meal_categories ORDER BY name ASC
`

func (q *Queries) ListMealCategories(ctx context.Context) ([]MealCategory, error) {
	rows, err := q.db.QueryContext(ctx, listMealCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealCategory
	for rows.Next() {
		var i MealCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemCategory = `-- name: UpdateItemCategory :one
UPDATE item_categories SET name = $1 WHERE id = $2 RETURNING id, name
`

type UpdateItemCategoryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateItemCategory(ctx context.Context, arg UpdateItemCategoryParams) (ItemCategory, error) {
	row := q.db.QueryRowContext(ctx, updateItemCategory, arg.Name, arg.ID)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateMealCategory = `-- name: UpdateMealCategory :one
UPDATE meal_categories SET name = $1 WHERE id = $2 RETURNING id, name
`

type UpdateMealCategoryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateMealCategory(ctx context.Context, arg UpdateMealCategoryParams) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, updateMealCategory, arg.Name, arg.ID)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
