// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grocery_operations.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const batchGetMeals = `-- name: BatchGetMeals :many
SELECT id, name, meal_category_id, servings FROM meals WHERE id = ANY($1::int[])
`

func (q *Queries) BatchGetMeals(ctx context.Context, dollar_1 []int32) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, batchGetMeals, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MealCategoryID,
			&i.Servings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryForItems = `-- name: GetInventoryForItems :many
SELECT 
  ii.item_id,
  ii.unit_id,
  ii.stored_amount
FROM inventory_items ii
WHERE ii.item_id = ANY($1::int[])
`

type GetInventoryForItemsRow struct {
	ItemID       int32          `json:"item_id"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	StoredAmount sql.NullString `json:"stored_amount"`
}

func (q *Queries) GetInventoryForItems(ctx context.Context, dollar_1 []int32) ([]GetInventoryForItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryForItems, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryForItemsRow
	for rows.Next() {
		var i GetInventoryForItemsRow
		if err := rows.Scan(&i.ItemID, &i.UnitID, &i.StoredAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealIngredientsForIds = `-- name: GetMealIngredientsForIds :many
SELECT 
  mi.meal_id,
  mi.ingredient_id,
  mi.unit_id,
  mi.required_amount,
  mi.is_seasoning,
  mi.depletes_slowly,
  mi.alternate_ingredient_id
FROM meal_ingredients mi
WHERE mi.meal_id = ANY($1::int[])
ORDER BY mi.meal_id, mi.id
`

type GetMealIngredientsForIdsRow struct {
	MealID                int32          `json:"meal_id"`
	IngredientID          int32          `json:"ingredient_id"`
	UnitID                sql.NullInt32  `json:"unit_id"`
	RequiredAmount        sql.NullString `json:"required_amount"`
	IsSeasoning           bool           `json:"is_seasoning"`
	DepletesSlowly        bool           `json:"depletes_slowly"`
	AlternateIngredientID sql.NullInt32  `json:"alternate_ingredient_id"`
}

func (q *Queries) GetMealIngredientsForIds(ctx context.Context, dollar_1 []int32) ([]GetMealIngredientsForIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMealIngredientsForIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealIngredientsForIdsRow
	for rows.Next() {
		var i GetMealIngredientsForIdsRow
		if err := rows.Scan(
			&i.MealID,
			&i.IngredientID,
			&i.UnitID,
			&i.RequiredAmount,
			&i.IsSeasoning,
			&i.DepletesSlowly,
			&i.AlternateIngredientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealServings = `-- name: GetMealServings :one
SELECT servings FROM meals WHERE id = $1
`

func (q *Queries) GetMealServings(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMealServings, id)
	var servings int32
	err := row.Scan(&servings)
	return servings, err
}

const getStoreItemsForItems = `-- name: GetStoreItemsForItems :many
SELECT 
  si.id,
  si.store_id,
  si.item_id,
  s.name as store_name,
  i.name as item_name,
  si.purchase_unit_id,
  si.inventory_unit_id,
  si.inventory_units_per_purchase,
  si.purchased_by_decimal,
  si.store_traversal_order,
  pu.name as purchase_unit_name,
  iu.name as inventory_unit_name
FROM store_items si
JOIN stores s ON si.store_id = s.id
JOIN items i ON si.item_id = i.id
LEFT JOIN units pu ON si.purchase_unit_id = pu.id
LEFT JOIN units iu ON si.inventory_unit_id = iu.id
WHERE si.item_id = ANY($1::int[])
ORDER BY s.id, si.store_traversal_order
`

type GetStoreItemsForItemsRow struct {
	ID                        int32          `json:"id"`
	StoreID                   int32          `json:"store_id"`
	ItemID                    int32          `json:"item_id"`
	StoreName                 string         `json:"store_name"`
	ItemName                  string         `json:"item_name"`
	PurchaseUnitID            sql.NullInt32  `json:"purchase_unit_id"`
	InventoryUnitID           sql.NullInt32  `json:"inventory_unit_id"`
	InventoryUnitsPerPurchase string         `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool           `json:"purchased_by_decimal"`
	StoreTraversalOrder       int32          `json:"store_traversal_order"`
	PurchaseUnitName          sql.NullString `json:"purchase_unit_name"`
	InventoryUnitName         sql.NullString `json:"inventory_unit_name"`
}

func (q *Queries) GetStoreItemsForItems(ctx context.Context, dollar_1 []int32) ([]GetStoreItemsForItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoreItemsForItems, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoreItemsForItemsRow
	for rows.Next() {
		var i GetStoreItemsForItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemID,
			&i.StoreName,
			&i.ItemName,
			&i.PurchaseUnitID,
			&i.InventoryUnitID,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.StoreTraversalOrder,
			&i.PurchaseUnitName,
			&i.InventoryUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryBatch = `-- name: UpdateInventoryBatch :one
UPDATE inventory_items SET stored_amount = $1 WHERE item_id = $2 RETURNING id, item_id, unit_id, stored_amount
`

type UpdateInventoryBatchParams struct {
	StoredAmount sql.NullString `json:"stored_amount"`
	ItemID       int32          `json:"item_id"`
}

func (q *Queries) UpdateInventoryBatch(ctx context.Context, arg UpdateInventoryBatchParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, updateInventoryBatch, arg.StoredAmount, arg.ItemID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UnitID,
		&i.StoredAmount,
	)
	return i, err
}
