// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (item_id, unit_id, stored_amount) VALUES ($1, $2, $3) RETURNING id, item_id, unit_id, stored_amount
`

type CreateInventoryItemParams struct {
	ItemID       int32          `json:"item_id"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	StoredAmount sql.NullString `json:"stored_amount"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem, arg.ItemID, arg.UnitID, arg.StoredAmount)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UnitID,
		&i.StoredAmount,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items WHERE item_id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, itemID int32) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryItem, itemID)
	return err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, item_id, unit_id, stored_amount FROM inventory_items WHERE id = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, id int32) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UnitID,
		&i.StoredAmount,
	)
	return i, err
}

const getInventoryItemByItemId = `-- name: GetInventoryItemByItemId :one
SELECT id, item_id, unit_id, stored_amount FROM inventory_items WHERE item_id = $1
`

func (q *Queries) GetInventoryItemByItemId(ctx context.Context, itemID int32) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItemByItemId, itemID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UnitID,
		&i.StoredAmount,
	)
	return i, err
}

const getInventoryItemWithItemInfo = `-- name: GetInventoryItemWithItemInfo :one
SELECT ii.id, ii.item_id, i.name, ii.unit_id, u.name as unit_name, ii.stored_amount 
FROM inventory_items ii
JOIN items i ON ii.item_id = i.id
LEFT JOIN units u ON ii.unit_id = u.id
WHERE ii.item_id = $1
`

type GetInventoryItemWithItemInfoRow struct {
	ID           int32          `json:"id"`
	ItemID       int32          `json:"item_id"`
	Name         string         `json:"name"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	UnitName     sql.NullString `json:"unit_name"`
	StoredAmount sql.NullString `json:"stored_amount"`
}

func (q *Queries) GetInventoryItemWithItemInfo(ctx context.Context, itemID int32) (GetInventoryItemWithItemInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItemWithItemInfo, itemID)
	var i GetInventoryItemWithItemInfoRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.StoredAmount,
	)
	return i, err
}

const getInventoryItemsWithItemInfo = `-- name: GetInventoryItemsWithItemInfo :many
SELECT ii.id, ii.item_id, i.name, ii.unit_id, u.name as unit_name, ii.stored_amount 
FROM inventory_items ii
JOIN items i ON ii.item_id = i.id
LEFT JOIN units u ON ii.unit_id = u.id
ORDER BY i.name ASC
`

type GetInventoryItemsWithItemInfoRow struct {
	ID           int32          `json:"id"`
	ItemID       int32          `json:"item_id"`
	Name         string         `json:"name"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	UnitName     sql.NullString `json:"unit_name"`
	StoredAmount sql.NullString `json:"stored_amount"`
}

func (q *Queries) GetInventoryItemsWithItemInfo(ctx context.Context) ([]GetInventoryItemsWithItemInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryItemsWithItemInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryItemsWithItemInfoRow
	for rows.Next() {
		var i GetInventoryItemsWithItemInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.UnitID,
			&i.UnitName,
			&i.StoredAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, item_id, unit_id, stored_amount FROM inventory_items ORDER BY item_id ASC LIMIT $1 OFFSET $2
`

type ListInventoryItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInventoryItems(ctx context.Context, arg ListInventoryItemsParams) ([]InventoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.UnitID,
			&i.StoredAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryItemsCount = `-- name: ListInventoryItemsCount :one
SELECT COUNT(*) as count FROM inventory_items
`

func (q *Queries) ListInventoryItemsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listInventoryItemsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :exec
UPDATE inventory_items SET unit_id = $1, stored_amount = $2 WHERE item_id = $3
`

type UpdateInventoryItemParams struct {
	UnitID       sql.NullInt32  `json:"unit_id"`
	StoredAmount sql.NullString `json:"stored_amount"`
	ItemID       int32          `json:"item_id"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) error {
	_, err := q.db.ExecContext(ctx, updateInventoryItem, arg.UnitID, arg.StoredAmount, arg.ItemID)
	return err
}

const updateInventoryStoredAmount = `-- name: UpdateInventoryStoredAmount :exec
UPDATE inventory_items SET stored_amount = $1 WHERE item_id = $2
`

type UpdateInventoryStoredAmountParams struct {
	StoredAmount sql.NullString `json:"stored_amount"`
	ItemID       int32          `json:"item_id"`
}

func (q *Queries) UpdateInventoryStoredAmount(ctx context.Context, arg UpdateInventoryStoredAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateInventoryStoredAmount, arg.StoredAmount, arg.ItemID)
	return err
}
