// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"
)

const addItemCategory = `-- name: AddItemCategory :exec
INSERT INTO item_category_mappings (item_id, category_id) VALUES ($1, $2)
`

type AddItemCategoryParams struct {
	ItemID     int32 `json:"item_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) AddItemCategory(ctx context.Context, arg AddItemCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addItemCategory, arg.ItemID, arg.CategoryID)
	return err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateItem(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, name)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, name FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getItemByName = `-- name: GetItemByName :one
SELECT id, name FROM items WHERE name = $1
`

func (q *Queries) GetItemByName(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByName, name)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getItemCategories = `-- name: GetItemCategories :many
SELECT ic.id, ic.name FROM item_categories ic
JOIN item_category_mappings icm ON ic.id = icm.category_id
WHERE icm.item_id = $1
ORDER BY ic.name ASC
`

func (q *Queries) GetItemCategories(ctx context.Context, itemID int32) ([]ItemCategory, error) {
	rows, err := q.db.QueryContext(ctx, getItemCategories, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemCategory
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name FROM items ORDER BY name ASC LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategory = `-- name: ListItemsByCategory :many
SELECT DISTINCT i.id, i.name FROM items i
JOIN item_category_mappings icm ON i.id = icm.item_id
WHERE icm.category_id = $1
ORDER BY i.name ASC LIMIT $2 OFFSET $3
`

type ListItemsByCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategoryCount = `-- name: ListItemsByCategoryCount :one
SELECT COUNT(DISTINCT i.id) as count FROM items i
JOIN item_category_mappings icm ON i.id = icm.item_id
WHERE icm.category_id = $1
`

func (q *Queries) ListItemsByCategoryCount(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, listItemsByCategoryCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listItemsCount = `-- name: ListItemsCount :one
SELECT COUNT(*) as count FROM items
`

func (q *Queries) ListItemsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listItemsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeAllItemCategories = `-- name: RemoveAllItemCategories :exec
DELETE FROM item_category_mappings WHERE item_id = $1
`

func (q *Queries) RemoveAllItemCategories(ctx context.Context, itemID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllItemCategories, itemID)
	return err
}

const removeItemCategory = `-- name: RemoveItemCategory :exec
DELETE FROM item_category_mappings WHERE item_id = $1 AND category_id = $2
`

type RemoveItemCategoryParams struct {
	ItemID     int32 `json:"item_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) RemoveItemCategory(ctx context.Context, arg RemoveItemCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeItemCategory, arg.ItemID, arg.CategoryID)
	return err
}

const searchItems = `-- name: SearchItems :many
SELECT id, name FROM items WHERE name ILIKE $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type SearchItemsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsCount = `-- name: SearchItemsCount :one
SELECT COUNT(*) as count FROM items WHERE name ILIKE $1
`

func (q *Queries) SearchItemsCount(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchItemsCount, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET name = $1 WHERE id = $2 RETURNING id, name
`

type UpdateItemParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem, arg.Name, arg.ID)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
