// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_ingredients.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createMealIngredient = `-- name: CreateMealIngredient :one
INSERT INTO meal_ingredients (meal_id, ingredient_id, unit_id, required_amount, is_seasoning, depletes_slowly, alternate_ingredient_id) 
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, meal_id, ingredient_id, unit_id, required_amount, is_seasoning, depletes_slowly, alternate_ingredient_id
`

type CreateMealIngredientParams struct {
	MealID                int32          `json:"meal_id"`
	IngredientID          int32          `json:"ingredient_id"`
	UnitID                sql.NullInt32  `json:"unit_id"`
	RequiredAmount        sql.NullString `json:"required_amount"`
	IsSeasoning           bool           `json:"is_seasoning"`
	DepletesSlowly        bool           `json:"depletes_slowly"`
	AlternateIngredientID sql.NullInt32  `json:"alternate_ingredient_id"`
}

func (q *Queries) CreateMealIngredient(ctx context.Context, arg CreateMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRowContext(ctx, createMealIngredient,
		arg.MealID,
		arg.IngredientID,
		arg.UnitID,
		arg.RequiredAmount,
		arg.IsSeasoning,
		arg.DepletesSlowly,
		arg.AlternateIngredientID,
	)
	var i MealIngredient
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.IngredientID,
		&i.UnitID,
		&i.RequiredAmount,
		&i.IsSeasoning,
		&i.DepletesSlowly,
		&i.AlternateIngredientID,
	)
	return i, err
}

const deleteMealIngredient = `-- name: DeleteMealIngredient :exec
DELETE FROM meal_ingredients WHERE id = $1
`

func (q *Queries) DeleteMealIngredient(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMealIngredient, id)
	return err
}

const deleteMealIngredientsByMealId = `-- name: DeleteMealIngredientsByMealId :exec
DELETE FROM meal_ingredients WHERE meal_id = $1
`

func (q *Queries) DeleteMealIngredientsByMealId(ctx context.Context, mealID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMealIngredientsByMealId, mealID)
	return err
}

const getMealIngredient = `-- name: GetMealIngredient :one
SELECT id, meal_id, ingredient_id, unit_id, required_amount, is_seasoning, depletes_slowly, alternate_ingredient_id 
FROM meal_ingredients WHERE id = $1
`

func (q *Queries) GetMealIngredient(ctx context.Context, id int32) (MealIngredient, error) {
	row := q.db.QueryRowContext(ctx, getMealIngredient, id)
	var i MealIngredient
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.IngredientID,
		&i.UnitID,
		&i.RequiredAmount,
		&i.IsSeasoning,
		&i.DepletesSlowly,
		&i.AlternateIngredientID,
	)
	return i, err
}

const getMealIngredientsWithDetails = `-- name: GetMealIngredientsWithDetails :many
SELECT 
  mi.id, 
  mi.meal_id, 
  mi.ingredient_id, 
  i.name as ingredient_name,
  mi.unit_id, 
  u.name as unit_name,
  mi.required_amount, 
  mi.is_seasoning, 
  mi.depletes_slowly, 
  mi.alternate_ingredient_id,
  ai.name as alternate_ingredient_name
FROM meal_ingredients mi
JOIN items i ON mi.ingredient_id = i.id
LEFT JOIN units u ON mi.unit_id = u.id
LEFT JOIN items ai ON mi.alternate_ingredient_id = ai.id
WHERE mi.meal_id = $1
ORDER BY mi.id ASC
`

type GetMealIngredientsWithDetailsRow struct {
	ID                      int32          `json:"id"`
	MealID                  int32          `json:"meal_id"`
	IngredientID            int32          `json:"ingredient_id"`
	IngredientName          string         `json:"ingredient_name"`
	UnitID                  sql.NullInt32  `json:"unit_id"`
	UnitName                sql.NullString `json:"unit_name"`
	RequiredAmount          sql.NullString `json:"required_amount"`
	IsSeasoning             bool           `json:"is_seasoning"`
	DepletesSlowly          bool           `json:"depletes_slowly"`
	AlternateIngredientID   sql.NullInt32  `json:"alternate_ingredient_id"`
	AlternateIngredientName sql.NullString `json:"alternate_ingredient_name"`
}

func (q *Queries) GetMealIngredientsWithDetails(ctx context.Context, mealID int32) ([]GetMealIngredientsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMealIngredientsWithDetails, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealIngredientsWithDetailsRow
	for rows.Next() {
		var i GetMealIngredientsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.IngredientID,
			&i.IngredientName,
			&i.UnitID,
			&i.UnitName,
			&i.RequiredAmount,
			&i.IsSeasoning,
			&i.DepletesSlowly,
			&i.AlternateIngredientID,
			&i.AlternateIngredientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealIngredients = `-- name: ListMealIngredients :many
SELECT id, meal_id, ingredient_id, unit_id, required_amount, is_seasoning, depletes_slowly, alternate_ingredient_id 
FROM meal_ingredients WHERE meal_id = $1 ORDER BY id ASC
`

func (q *Queries) ListMealIngredients(ctx context.Context, mealID int32) ([]MealIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listMealIngredients, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealIngredient
	for rows.Next() {
		var i MealIngredient
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.IngredientID,
			&i.UnitID,
			&i.RequiredAmount,
			&i.IsSeasoning,
			&i.DepletesSlowly,
			&i.AlternateIngredientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealIngredientsForMultipleMeals = `-- name: ListMealIngredientsForMultipleMeals :many
SELECT 
  mi.meal_id,
  mi.ingredient_id,
  mi.unit_id,
  mi.required_amount,
  mi.alternate_ingredient_id
FROM meal_ingredients mi
WHERE mi.meal_id = ANY($1::int[])
`

type ListMealIngredientsForMultipleMealsRow struct {
	MealID                int32          `json:"meal_id"`
	IngredientID          int32          `json:"ingredient_id"`
	UnitID                sql.NullInt32  `json:"unit_id"`
	RequiredAmount        sql.NullString `json:"required_amount"`
	AlternateIngredientID sql.NullInt32  `json:"alternate_ingredient_id"`
}

func (q *Queries) ListMealIngredientsForMultipleMeals(ctx context.Context, dollar_1 []int32) ([]ListMealIngredientsForMultipleMealsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealIngredientsForMultipleMeals, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealIngredientsForMultipleMealsRow
	for rows.Next() {
		var i ListMealIngredientsForMultipleMealsRow
		if err := rows.Scan(
			&i.MealID,
			&i.IngredientID,
			&i.UnitID,
			&i.RequiredAmount,
			&i.AlternateIngredientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMealIngredient = `-- name: UpdateMealIngredient :exec
UPDATE meal_ingredients 
SET ingredient_id = $1, unit_id = $2, required_amount = $3, is_seasoning = $4, depletes_slowly = $5, alternate_ingredient_id = $6 
WHERE id = $7
`

type UpdateMealIngredientParams struct {
	IngredientID          int32          `json:"ingredient_id"`
	UnitID                sql.NullInt32  `json:"unit_id"`
	RequiredAmount        sql.NullString `json:"required_amount"`
	IsSeasoning           bool           `json:"is_seasoning"`
	DepletesSlowly        bool           `json:"depletes_slowly"`
	AlternateIngredientID sql.NullInt32  `json:"alternate_ingredient_id"`
	ID                    int32          `json:"id"`
}

func (q *Queries) UpdateMealIngredient(ctx context.Context, arg UpdateMealIngredientParams) error {
	_, err := q.db.ExecContext(ctx, updateMealIngredient,
		arg.IngredientID,
		arg.UnitID,
		arg.RequiredAmount,
		arg.IsSeasoning,
		arg.DepletesSlowly,
		arg.AlternateIngredientID,
		arg.ID,
	)
	return err
}
