// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package sqlc

import (
	"context"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name, meal_category_id, servings) VALUES ($1, $2, $3) RETURNING id, name, meal_category_id, servings
`

type CreateMealParams struct {
	Name           string `json:"name"`
	MealCategoryID int32  `json:"meal_category_id"`
	Servings       int32  `json:"servings"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal, arg.Name, arg.MealCategoryID, arg.Servings)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MealCategoryID,
		&i.Servings,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, name, meal_category_id, servings FROM meals WHERE id = $1
`

func (q *Queries) GetMeal(ctx context.Context, id int32) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MealCategoryID,
		&i.Servings,
	)
	return i, err
}

const getMealByName = `-- name: GetMealByName :one
SELECT id, name, meal_category_id, servings FROM meals WHERE name = $1
`

func (q *Queries) GetMealByName(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMealByName, name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MealCategoryID,
		&i.Servings,
	)
	return i, err
}

const getMealWithCategory = `-- name: GetMealWithCategory :one
SELECT m.id, m.name, m.meal_category_id, mc.name as category_name, m.servings 
FROM meals m
JOIN meal_categories mc ON m.meal_category_id = mc.id
WHERE m.id = $1
`

type GetMealWithCategoryRow struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	MealCategoryID int32  `json:"meal_category_id"`
	CategoryName   string `json:"category_name"`
	Servings       int32  `json:"servings"`
}

func (q *Queries) GetMealWithCategory(ctx context.Context, id int32) (GetMealWithCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getMealWithCategory, id)
	var i GetMealWithCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MealCategoryID,
		&i.CategoryName,
		&i.Servings,
	)
	return i, err
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, meal_category_id, servings FROM meals ORDER BY name ASC LIMIT $1 OFFSET $2
`

type ListMealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMeals(ctx context.Context, arg ListMealsParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MealCategoryID,
			&i.Servings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByCategory = `-- name: ListMealsByCategory :many
SELECT id, name, meal_category_id, servings FROM meals WHERE meal_category_id = $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type ListMealsByCategoryParams struct {
	MealCategoryID int32 `json:"meal_category_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListMealsByCategory(ctx context.Context, arg ListMealsByCategoryParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMealsByCategory, arg.MealCategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MealCategoryID,
			&i.Servings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByCategoryCount = `-- name: ListMealsByCategoryCount :one
SELECT COUNT(*) as count FROM meals WHERE meal_category_id = $1
`

func (q *Queries) ListMealsByCategoryCount(ctx context.Context, mealCategoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, listMealsByCategoryCount, mealCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMealsCount = `-- name: ListMealsCount :one
SELECT COUNT(*) as count FROM meals
`

func (q *Queries) ListMealsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listMealsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchMeals = `-- name: SearchMeals :many
SELECT id, name, meal_category_id, servings FROM meals WHERE name ILIKE $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type SearchMealsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchMeals(ctx context.Context, arg SearchMealsParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, searchMeals, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MealCategoryID,
			&i.Servings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMealsCount = `-- name: SearchMealsCount :one
SELECT COUNT(*) as count FROM meals WHERE name ILIKE $1
`

func (q *Queries) SearchMealsCount(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchMealsCount, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMeal = `-- name: UpdateMeal :exec
UPDATE meals SET name = $1, meal_category_id = $2, servings = $3 WHERE id = $4
`

type UpdateMealParams struct {
	Name           string `json:"name"`
	MealCategoryID int32  `json:"meal_category_id"`
	Servings       int32  `json:"servings"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.ExecContext(ctx, updateMeal,
		arg.Name,
		arg.MealCategoryID,
		arg.Servings,
		arg.ID,
	)
	return err
}
