// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type InventoryItem struct {
	ID           int32          `json:"id"`
	ItemID       int32          `json:"item_id"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	StoredAmount sql.NullString `json:"stored_amount"`
}

type Item struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type ItemCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type ItemCategoryMapping struct {
	ItemID     int32 `json:"item_id"`
	CategoryID int32 `json:"category_id"`
}

type Meal struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	MealCategoryID int32  `json:"meal_category_id"`
	Servings       int32  `json:"servings"`
}

type MealCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type MealIngredient struct {
	ID                    int32          `json:"id"`
	MealID                int32          `json:"meal_id"`
	IngredientID          int32          `json:"ingredient_id"`
	UnitID                sql.NullInt32  `json:"unit_id"`
	RequiredAmount        sql.NullString `json:"required_amount"`
	IsSeasoning           bool           `json:"is_seasoning"`
	DepletesSlowly        bool           `json:"depletes_slowly"`
	AlternateIngredientID sql.NullInt32  `json:"alternate_ingredient_id"`
}

type ShoppingList struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type ShoppingListItem struct {
	ID                int32          `json:"id"`
	ShoppingListID    int32          `json:"shopping_list_id"`
	StoreItemID       sql.NullInt32  `json:"store_item_id"`
	PurchaseQuantity  sql.NullString `json:"purchase_quantity"`
	Note              sql.NullString `json:"note"`
	CustomItemName    sql.NullString `json:"custom_item_name"`
	ShoppingListOrder int32          `json:"shopping_list_order"`
}

type Store struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type StoreItem struct {
	ID                        int32         `json:"id"`
	StoreID                   int32         `json:"store_id"`
	ItemID                    int32         `json:"item_id"`
	PurchaseUnitID            sql.NullInt32 `json:"purchase_unit_id"`
	InventoryUnitID           sql.NullInt32 `json:"inventory_unit_id"`
	InventoryUnitsPerPurchase string        `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool          `json:"purchased_by_decimal"`
	IsFavorite                bool          `json:"is_favorite"`
	StoreTraversalOrder       int32         `json:"store_traversal_order"`
}

type Unit struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
