// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_list_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createShoppingListItem = `-- name: CreateShoppingListItem :one
INSERT INTO shopping_list_items (shopping_list_id, store_item_id, purchase_quantity, note, custom_item_name, shopping_list_order) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, shopping_list_id, store_item_id, purchase_quantity, note, custom_item_name, shopping_list_order
`

type CreateShoppingListItemParams struct {
	ShoppingListID    int32          `json:"shopping_list_id"`
	StoreItemID       sql.NullInt32  `json:"store_item_id"`
	PurchaseQuantity  sql.NullString `json:"purchase_quantity"`
	Note              sql.NullString `json:"note"`
	CustomItemName    sql.NullString `json:"custom_item_name"`
	ShoppingListOrder int32          `json:"shopping_list_order"`
}

func (q *Queries) CreateShoppingListItem(ctx context.Context, arg CreateShoppingListItemParams) (ShoppingListItem, error) {
	row := q.db.QueryRowContext(ctx, createShoppingListItem,
		arg.ShoppingListID,
		arg.StoreItemID,
		arg.PurchaseQuantity,
		arg.Note,
		arg.CustomItemName,
		arg.ShoppingListOrder,
	)
	var i ShoppingListItem
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.StoreItemID,
		&i.PurchaseQuantity,
		&i.Note,
		&i.CustomItemName,
		&i.ShoppingListOrder,
	)
	return i, err
}

const deleteShoppingListItem = `-- name: DeleteShoppingListItem :exec
DELETE FROM shopping_list_items WHERE id = $1
`

func (q *Queries) DeleteShoppingListItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingListItem, id)
	return err
}

const deleteShoppingListItemsByShoppingListId = `-- name: DeleteShoppingListItemsByShoppingListId :exec
DELETE FROM shopping_list_items WHERE shopping_list_id = $1
`

func (q *Queries) DeleteShoppingListItemsByShoppingListId(ctx context.Context, shoppingListID int32) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingListItemsByShoppingListId, shoppingListID)
	return err
}

const getMaxShoppingListOrder = `-- name: GetMaxShoppingListOrder :one
SELECT COALESCE(MAX(shopping_list_order), 0) as max_order FROM shopping_list_items WHERE shopping_list_id = $1
`

func (q *Queries) GetMaxShoppingListOrder(ctx context.Context, shoppingListID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxShoppingListOrder, shoppingListID)
	var max_order interface{}
	err := row.Scan(&max_order)
	return max_order, err
}

const getShoppingListItem = `-- name: GetShoppingListItem :one
SELECT id, shopping_list_id, store_item_id, purchase_quantity, note, custom_item_name, shopping_list_order 
FROM shopping_list_items WHERE id = $1
`

func (q *Queries) GetShoppingListItem(ctx context.Context, id int32) (ShoppingListItem, error) {
	row := q.db.QueryRowContext(ctx, getShoppingListItem, id)
	var i ShoppingListItem
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.StoreItemID,
		&i.PurchaseQuantity,
		&i.Note,
		&i.CustomItemName,
		&i.ShoppingListOrder,
	)
	return i, err
}

const getShoppingListItemsWithDetails = `-- name: GetShoppingListItemsWithDetails :many
SELECT 
  sli.id, 
  sli.shopping_list_id, 
  sli.store_item_id, 
  i.name as item_name,
  s.name as store_name,
  si.store_traversal_order,
  sli.purchase_quantity, 
  pu.name as purchase_unit_name,
  sli.note, 
  sli.custom_item_name,
  sli.shopping_list_order
FROM shopping_list_items sli
LEFT JOIN store_items si ON sli.store_item_id = si.id
LEFT JOIN items i ON si.item_id = i.id
LEFT JOIN stores s ON si.store_id = s.id
LEFT JOIN units pu ON si.purchase_unit_id = pu.id
WHERE sli.shopping_list_id = $1
ORDER BY s.name ASC, si.store_traversal_order ASC, sli.shopping_list_order ASC
`

type GetShoppingListItemsWithDetailsRow struct {
	ID                  int32          `json:"id"`
	ShoppingListID      int32          `json:"shopping_list_id"`
	StoreItemID         sql.NullInt32  `json:"store_item_id"`
	ItemName            sql.NullString `json:"item_name"`
	StoreName           sql.NullString `json:"store_name"`
	StoreTraversalOrder sql.NullInt32  `json:"store_traversal_order"`
	PurchaseQuantity    sql.NullString `json:"purchase_quantity"`
	PurchaseUnitName    sql.NullString `json:"purchase_unit_name"`
	Note                sql.NullString `json:"note"`
	CustomItemName      sql.NullString `json:"custom_item_name"`
	ShoppingListOrder   int32          `json:"shopping_list_order"`
}

func (q *Queries) GetShoppingListItemsWithDetails(ctx context.Context, shoppingListID int32) ([]GetShoppingListItemsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingListItemsWithDetails, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShoppingListItemsWithDetailsRow
	for rows.Next() {
		var i GetShoppingListItemsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.StoreItemID,
			&i.ItemName,
			&i.StoreName,
			&i.StoreTraversalOrder,
			&i.PurchaseQuantity,
			&i.PurchaseUnitName,
			&i.Note,
			&i.CustomItemName,
			&i.ShoppingListOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingListItemsWithDetailsSimple = `-- name: GetShoppingListItemsWithDetailsSimple :many
SELECT 
  sli.id, 
  sli.shopping_list_id, 
  sli.store_item_id, 
  sli.purchase_quantity, 
  sli.note, 
  sli.custom_item_name,
  sli.shopping_list_order
FROM shopping_list_items sli
WHERE sli.shopping_list_id = $1
ORDER BY sli.shopping_list_order ASC
`

func (q *Queries) GetShoppingListItemsWithDetailsSimple(ctx context.Context, shoppingListID int32) ([]ShoppingListItem, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingListItemsWithDetailsSimple, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingListItem
	for rows.Next() {
		var i ShoppingListItem
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.StoreItemID,
			&i.PurchaseQuantity,
			&i.Note,
			&i.CustomItemName,
			&i.ShoppingListOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingListItems = `-- name: ListShoppingListItems :many
SELECT id, shopping_list_id, store_item_id, purchase_quantity, note, custom_item_name, shopping_list_order 
FROM shopping_list_items WHERE shopping_list_id = $1 ORDER BY shopping_list_order ASC
`

func (q *Queries) ListShoppingListItems(ctx context.Context, shoppingListID int32) ([]ShoppingListItem, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingListItems, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingListItem
	for rows.Next() {
		var i ShoppingListItem
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.StoreItemID,
			&i.PurchaseQuantity,
			&i.Note,
			&i.CustomItemName,
			&i.ShoppingListOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingListItem = `-- name: UpdateShoppingListItem :exec
UPDATE shopping_list_items 
SET store_item_id = $1, purchase_quantity = $2, note = $3, custom_item_name = $4, shopping_list_order = $5 
WHERE id = $6
`

type UpdateShoppingListItemParams struct {
	StoreItemID       sql.NullInt32  `json:"store_item_id"`
	PurchaseQuantity  sql.NullString `json:"purchase_quantity"`
	Note              sql.NullString `json:"note"`
	CustomItemName    sql.NullString `json:"custom_item_name"`
	ShoppingListOrder int32          `json:"shopping_list_order"`
	ID                int32          `json:"id"`
}

func (q *Queries) UpdateShoppingListItem(ctx context.Context, arg UpdateShoppingListItemParams) error {
	_, err := q.db.ExecContext(ctx, updateShoppingListItem,
		arg.StoreItemID,
		arg.PurchaseQuantity,
		arg.Note,
		arg.CustomItemName,
		arg.ShoppingListOrder,
		arg.ID,
	)
	return err
}

const updateShoppingListItemsOrder = `-- name: UpdateShoppingListItemsOrder :exec
UPDATE shopping_list_items SET shopping_list_order = $1 WHERE id = $2
`

type UpdateShoppingListItemsOrderParams struct {
	ShoppingListOrder int32 `json:"shopping_list_order"`
	ID                int32 `json:"id"`
}

func (q *Queries) UpdateShoppingListItemsOrder(ctx context.Context, arg UpdateShoppingListItemsOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateShoppingListItemsOrder, arg.ShoppingListOrder, arg.ID)
	return err
}
