// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_lists.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_lists (name, created_at) VALUES ($1, CURRENT_TIMESTAMP) RETURNING id, name, created_at
`

func (q *Queries) CreateShoppingList(ctx context.Context, name string) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, createShoppingList, name)
	var i ShoppingList
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteShoppingList = `-- name: DeleteShoppingList :exec
DELETE FROM shopping_lists WHERE id = $1
`

func (q *Queries) DeleteShoppingList(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingList, id)
	return err
}

const getShoppingList = `-- name: GetShoppingList :one
SELECT id, name, created_at FROM shopping_lists WHERE id = $1
`

func (q *Queries) GetShoppingList(ctx context.Context, id int32) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingList, id)
	var i ShoppingList
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getShoppingListsContainingStoreItem = `-- name: GetShoppingListsContainingStoreItem :many
SELECT DISTINCT sl.id, sl.name, sl.created_at FROM shopping_lists sl
JOIN shopping_list_items sli ON sl.id = sli.shopping_list_id
WHERE sli.store_item_id = $1
ORDER BY sl.created_at DESC LIMIT $2 OFFSET $3
`

type GetShoppingListsContainingStoreItemParams struct {
	StoreItemID sql.NullInt32 `json:"store_item_id"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

func (q *Queries) GetShoppingListsContainingStoreItem(ctx context.Context, arg GetShoppingListsContainingStoreItemParams) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingListsContainingStoreItem, arg.StoreItemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingListsContainingStoreItemAsc = `-- name: GetShoppingListsContainingStoreItemAsc :many
SELECT DISTINCT sl.id, sl.name, sl.created_at FROM shopping_lists sl
JOIN shopping_list_items sli ON sl.id = sli.shopping_list_id
WHERE sli.store_item_id = $1
ORDER BY sl.created_at ASC LIMIT $2 OFFSET $3
`

type GetShoppingListsContainingStoreItemAscParams struct {
	StoreItemID sql.NullInt32 `json:"store_item_id"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

func (q *Queries) GetShoppingListsContainingStoreItemAsc(ctx context.Context, arg GetShoppingListsContainingStoreItemAscParams) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingListsContainingStoreItemAsc, arg.StoreItemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingListsContainingStoreItemCount = `-- name: GetShoppingListsContainingStoreItemCount :one
SELECT COUNT(DISTINCT sl.id) as count FROM shopping_lists sl
JOIN shopping_list_items sli ON sl.id = sli.shopping_list_id
WHERE sli.store_item_id = $1
`

func (q *Queries) GetShoppingListsContainingStoreItemCount(ctx context.Context, storeItemID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getShoppingListsContainingStoreItemCount, storeItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listShoppingLists = `-- name: ListShoppingLists :many
SELECT id, name, created_at FROM shopping_lists ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListShoppingListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShoppingLists(ctx context.Context, arg ListShoppingListsParams) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingListsAsc = `-- name: ListShoppingListsAsc :many
SELECT id, name, created_at FROM shopping_lists ORDER BY created_at ASC LIMIT $1 OFFSET $2
`

type ListShoppingListsAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShoppingListsAsc(ctx context.Context, arg ListShoppingListsAscParams) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingListsAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingListsByMostRecent = `-- name: ListShoppingListsByMostRecent :many
SELECT id, name, created_at FROM shopping_lists ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListShoppingListsByMostRecent(ctx context.Context, limit int32) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingListsByMostRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingListsCount = `-- name: ListShoppingListsCount :one
SELECT COUNT(*) as count FROM shopping_lists
`

func (q *Queries) ListShoppingListsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listShoppingListsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateShoppingList = `-- name: UpdateShoppingList :one
UPDATE shopping_lists SET name = $1 WHERE id = $2 RETURNING id, name, created_at
`

type UpdateShoppingListParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateShoppingList(ctx context.Context, arg UpdateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, updateShoppingList, arg.Name, arg.ID)
	var i ShoppingList
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
