// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stores.sql

package sqlc

import (
	"context"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateStore(ctx context.Context, name string) (Store, error) {
	row := q.db.QueryRowContext(ctx, createStore, name)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStore, id)
	return err
}

const getStore = `-- name: GetStore :one
SELECT id, name FROM stores WHERE id = $1
`

func (q *Queries) GetStore(ctx context.Context, id int32) (Store, error) {
	row := q.db.QueryRowContext(ctx, getStore, id)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getStoreByName = `-- name: GetStoreByName :one
SELECT id, name FROM stores WHERE name = $1
`

func (q *Queries) GetStoreByName(ctx context.Context, name string) (Store, error) {
	row := q.db.QueryRowContext(ctx, getStoreByName, name)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listStores = `-- name: ListStores :many
SELECT id, name FROM stores ORDER BY name ASC
`

func (q *Queries) ListStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresAsc = `-- name: ListStoresAsc :many
SELECT id, name FROM stores ORDER BY name ASC LIMIT $1 OFFSET $2
`

type ListStoresAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStoresAsc(ctx context.Context, arg ListStoresAscParams) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, listStoresAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresCount = `-- name: ListStoresCount :one
SELECT COUNT(*) as count FROM stores
`

func (q *Queries) ListStoresCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listStoresCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStoresDesc = `-- name: ListStoresDesc :many
SELECT id, name FROM stores ORDER BY name DESC LIMIT $1 OFFSET $2
`

type ListStoresDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStoresDesc(ctx context.Context, arg ListStoresDescParams) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, listStoresDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores SET name = $1 WHERE id = $2 RETURNING id, name
`

type UpdateStoreParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, updateStore, arg.Name, arg.ID)
	var i Store
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
