// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createStoreItem = `-- name: CreateStoreItem :one
INSERT INTO store_items (store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) 
RETURNING id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order
`

type CreateStoreItemParams struct {
	StoreID                   int32         `json:"store_id"`
	ItemID                    int32         `json:"item_id"`
	PurchaseUnitID            sql.NullInt32 `json:"purchase_unit_id"`
	InventoryUnitID           sql.NullInt32 `json:"inventory_unit_id"`
	InventoryUnitsPerPurchase string        `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool          `json:"purchased_by_decimal"`
	IsFavorite                bool          `json:"is_favorite"`
	StoreTraversalOrder       int32         `json:"store_traversal_order"`
}

func (q *Queries) CreateStoreItem(ctx context.Context, arg CreateStoreItemParams) (StoreItem, error) {
	row := q.db.QueryRowContext(ctx, createStoreItem,
		arg.StoreID,
		arg.ItemID,
		arg.PurchaseUnitID,
		arg.InventoryUnitID,
		arg.InventoryUnitsPerPurchase,
		arg.PurchasedByDecimal,
		arg.IsFavorite,
		arg.StoreTraversalOrder,
	)
	var i StoreItem
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ItemID,
		&i.PurchaseUnitID,
		&i.InventoryUnitID,
		&i.InventoryUnitsPerPurchase,
		&i.PurchasedByDecimal,
		&i.IsFavorite,
		&i.StoreTraversalOrder,
	)
	return i, err
}

const deleteStoreItem = `-- name: DeleteStoreItem :exec
DELETE FROM store_items WHERE id = $1
`

func (q *Queries) DeleteStoreItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStoreItem, id)
	return err
}

const getStoreItem = `-- name: GetStoreItem :one
SELECT id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order 
FROM store_items WHERE id = $1
`

func (q *Queries) GetStoreItem(ctx context.Context, id int32) (StoreItem, error) {
	row := q.db.QueryRowContext(ctx, getStoreItem, id)
	var i StoreItem
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ItemID,
		&i.PurchaseUnitID,
		&i.InventoryUnitID,
		&i.InventoryUnitsPerPurchase,
		&i.PurchasedByDecimal,
		&i.IsFavorite,
		&i.StoreTraversalOrder,
	)
	return i, err
}

const getStoreItemsByStoreWithDetails = `-- name: GetStoreItemsByStoreWithDetails :many
SELECT 
  si.id, 
  si.store_id, 
  si.item_id, 
  i.name as item_name,
  si.purchase_unit_id, 
  pu.name as purchase_unit_name,
  si.inventory_unit_id, 
  iu.name as inventory_unit_name,
  si.inventory_units_per_purchase, 
  si.purchased_by_decimal, 
  si.is_favorite, 
  si.store_traversal_order
FROM store_items si
JOIN items i ON si.item_id = i.id
LEFT JOIN units pu ON si.purchase_unit_id = pu.id
LEFT JOIN units iu ON si.inventory_unit_id = iu.id
WHERE si.store_id = $1
ORDER BY si.store_traversal_order ASC
`

type GetStoreItemsByStoreWithDetailsRow struct {
	ID                        int32          `json:"id"`
	StoreID                   int32          `json:"store_id"`
	ItemID                    int32          `json:"item_id"`
	ItemName                  string         `json:"item_name"`
	PurchaseUnitID            sql.NullInt32  `json:"purchase_unit_id"`
	PurchaseUnitName          sql.NullString `json:"purchase_unit_name"`
	InventoryUnitID           sql.NullInt32  `json:"inventory_unit_id"`
	InventoryUnitName         sql.NullString `json:"inventory_unit_name"`
	InventoryUnitsPerPurchase string         `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool           `json:"purchased_by_decimal"`
	IsFavorite                bool           `json:"is_favorite"`
	StoreTraversalOrder       int32          `json:"store_traversal_order"`
}

func (q *Queries) GetStoreItemsByStoreWithDetails(ctx context.Context, storeID int32) ([]GetStoreItemsByStoreWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoreItemsByStoreWithDetails, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoreItemsByStoreWithDetailsRow
	for rows.Next() {
		var i GetStoreItemsByStoreWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemID,
			&i.ItemName,
			&i.PurchaseUnitID,
			&i.PurchaseUnitName,
			&i.InventoryUnitID,
			&i.InventoryUnitName,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.IsFavorite,
			&i.StoreTraversalOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreItemsWithDetails = `-- name: GetStoreItemsWithDetails :many
SELECT 
  si.id, 
  si.store_id, 
  s.name as store_name,
  si.item_id, 
  i.name as item_name,
  si.purchase_unit_id, 
  pu.name as purchase_unit_name,
  si.inventory_unit_id, 
  iu.name as inventory_unit_name,
  si.inventory_units_per_purchase, 
  si.purchased_by_decimal, 
  si.is_favorite, 
  si.store_traversal_order
FROM store_items si
JOIN stores s ON si.store_id = s.id
JOIN items i ON si.item_id = i.id
LEFT JOIN units pu ON si.purchase_unit_id = pu.id
LEFT JOIN units iu ON si.inventory_unit_id = iu.id
ORDER BY si.store_id ASC, si.store_traversal_order ASC LIMIT $1 OFFSET $2
`

type GetStoreItemsWithDetailsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetStoreItemsWithDetailsRow struct {
	ID                        int32          `json:"id"`
	StoreID                   int32          `json:"store_id"`
	StoreName                 string         `json:"store_name"`
	ItemID                    int32          `json:"item_id"`
	ItemName                  string         `json:"item_name"`
	PurchaseUnitID            sql.NullInt32  `json:"purchase_unit_id"`
	PurchaseUnitName          sql.NullString `json:"purchase_unit_name"`
	InventoryUnitID           sql.NullInt32  `json:"inventory_unit_id"`
	InventoryUnitName         sql.NullString `json:"inventory_unit_name"`
	InventoryUnitsPerPurchase string         `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool           `json:"purchased_by_decimal"`
	IsFavorite                bool           `json:"is_favorite"`
	StoreTraversalOrder       int32          `json:"store_traversal_order"`
}

func (q *Queries) GetStoreItemsWithDetails(ctx context.Context, arg GetStoreItemsWithDetailsParams) ([]GetStoreItemsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoreItemsWithDetails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoreItemsWithDetailsRow
	for rows.Next() {
		var i GetStoreItemsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.StoreName,
			&i.ItemID,
			&i.ItemName,
			&i.PurchaseUnitID,
			&i.PurchaseUnitName,
			&i.InventoryUnitID,
			&i.InventoryUnitName,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.IsFavorite,
			&i.StoreTraversalOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreItemsWithDetailsCount = `-- name: GetStoreItemsWithDetailsCount :one
SELECT COUNT(*) as count FROM store_items
`

func (q *Queries) GetStoreItemsWithDetailsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStoreItemsWithDetailsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStoreItems = `-- name: ListStoreItems :many
SELECT id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order 
FROM store_items ORDER BY store_id ASC, store_traversal_order ASC LIMIT $1 OFFSET $2
`

type ListStoreItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStoreItems(ctx context.Context, arg ListStoreItemsParams) ([]StoreItem, error) {
	rows, err := q.db.QueryContext(ctx, listStoreItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreItem
	for rows.Next() {
		var i StoreItem
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemID,
			&i.PurchaseUnitID,
			&i.InventoryUnitID,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.IsFavorite,
			&i.StoreTraversalOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreItemsByStore = `-- name: ListStoreItemsByStore :many
SELECT id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order 
FROM store_items WHERE store_id = $1 ORDER BY store_traversal_order ASC
`

func (q *Queries) ListStoreItemsByStore(ctx context.Context, storeID int32) ([]StoreItem, error) {
	rows, err := q.db.QueryContext(ctx, listStoreItemsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreItem
	for rows.Next() {
		var i StoreItem
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemID,
			&i.PurchaseUnitID,
			&i.InventoryUnitID,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.IsFavorite,
			&i.StoreTraversalOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreItemsCount = `-- name: ListStoreItemsCount :one
SELECT COUNT(*) as count FROM store_items
`

func (q *Queries) ListStoreItemsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, listStoreItemsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchStoreItemsByStore = `-- name: SearchStoreItemsByStore :many
SELECT id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order 
FROM store_items 
WHERE store_id = $1 AND item_id IN (SELECT id FROM items WHERE name ILIKE $2)
ORDER BY store_traversal_order ASC
`

type SearchStoreItemsByStoreParams struct {
	StoreID int32  `json:"store_id"`
	Name    string `json:"name"`
}

func (q *Queries) SearchStoreItemsByStore(ctx context.Context, arg SearchStoreItemsByStoreParams) ([]StoreItem, error) {
	rows, err := q.db.QueryContext(ctx, searchStoreItemsByStore, arg.StoreID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreItem
	for rows.Next() {
		var i StoreItem
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ItemID,
			&i.PurchaseUnitID,
			&i.InventoryUnitID,
			&i.InventoryUnitsPerPurchase,
			&i.PurchasedByDecimal,
			&i.IsFavorite,
			&i.StoreTraversalOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreItem = `-- name: UpdateStoreItem :one
UPDATE store_items 
SET purchase_unit_id = $1, inventory_unit_id = $2, inventory_units_per_purchase = $3, purchased_by_decimal = $4, is_favorite = $5, store_traversal_order = $6 
WHERE id = $7 RETURNING id, store_id, item_id, purchase_unit_id, inventory_unit_id, inventory_units_per_purchase, purchased_by_decimal, is_favorite, store_traversal_order
`

type UpdateStoreItemParams struct {
	PurchaseUnitID            sql.NullInt32 `json:"purchase_unit_id"`
	InventoryUnitID           sql.NullInt32 `json:"inventory_unit_id"`
	InventoryUnitsPerPurchase string        `json:"inventory_units_per_purchase"`
	PurchasedByDecimal        bool          `json:"purchased_by_decimal"`
	IsFavorite                bool          `json:"is_favorite"`
	StoreTraversalOrder       int32         `json:"store_traversal_order"`
	ID                        int32         `json:"id"`
}

func (q *Queries) UpdateStoreItem(ctx context.Context, arg UpdateStoreItemParams) (StoreItem, error) {
	row := q.db.QueryRowContext(ctx, updateStoreItem,
		arg.PurchaseUnitID,
		arg.InventoryUnitID,
		arg.InventoryUnitsPerPurchase,
		arg.PurchasedByDecimal,
		arg.IsFavorite,
		arg.StoreTraversalOrder,
		arg.ID,
	)
	var i StoreItem
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ItemID,
		&i.PurchaseUnitID,
		&i.InventoryUnitID,
		&i.InventoryUnitsPerPurchase,
		&i.PurchasedByDecimal,
		&i.IsFavorite,
		&i.StoreTraversalOrder,
	)
	return i, err
}
